# Generated by Django 5.2.4 on 2025-07-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.IntegerField()),
                ('second_number', models.IntegerField()),
                ('operation', models.CharField(max_length=8)),
            ],
        ),
    ]
